"""create_initial_schema

Revision ID: 1b59c90005a4
Revises: 
Create Date: 2026-09-25 23:42:28.805072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b59c90005a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('mobility_level', sa.String(length=50), nullable=True),
    sa.Column('communication_preferences', sa.String(length=255), nullable=True),
    sa.Column('known_triggers', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_insights',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp_label', sa.String(length=50), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_category'), 'ai_insights', ['category'], unique=False)
    op.create_index(op.f('ix_ai_insights_patient_id'), 'ai_insights', ['patient_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('clinical_disclaimer', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_patient_id'), 'ai_recommendations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_status'), 'ai_recommendations', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('doctor', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('date_str', sa.String(length=50), nullable=False),
    sa.Column('time_str', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('behaviour_observations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('observation_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('intensity', sa.String(length=30), nullable=False),
    sa.Column('caregiver_action_taken', sa.String(length=255), nullable=True),
    sa.Column('possible_trigger', sa.String(length=255), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_observations_observation_type'), 'behaviour_observations', ['observation_type'], unique=False)
    op.create_index(op.f('ix_behaviour_observations_observed_at'), 'behaviour_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_behaviour_observations_patient_id'), 'behaviour_observations', ['patient_id'], unique=False)
    op.create_table('care_reports',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_date_label', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('adherence_rate', sa.Integer(), nullable=False),
    sa.Column('medication_rate', sa.Integer(), nullable=False),
    sa.Column('cognitive_rate', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.String(length=30), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_reports_patient_id'), 'care_reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_reports_report_type'), 'care_reports', ['report_type'], unique=False)
    op.create_table('care_team_members',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('permissions', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_team_members_patient_id'), 'care_team_members', ['patient_id'], unique=False)
    op.create_table('caregiver_patient',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('caregiver_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('relationship_name', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregiver_patient_caregiver_id'), 'caregiver_patient', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_caregiver_patient_patient_id'), 'caregiver_patient', ['patient_id'], unique=False)
    op.create_table('cognitive_activities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_activities_patient_id'), 'cognitive_activities', ['patient_id'], unique=False)
    op.create_table('doctor_care_plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=30), nullable=True),
    sa.Column('end_date', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_care_plans_patient_id'), 'doctor_care_plans', ['patient_id'], unique=False)
    op.create_table('familiar_people',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_recognized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_familiar_people_patient_id'), 'familiar_people', ['patient_id'], unique=False)
    op.create_table('habilitation_activities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=20), nullable=False),
    sa.Column('recommended_by', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habilitation_activities_patient_id'), 'habilitation_activities', ['patient_id'], unique=False)
    op.create_table('hydration_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hydration_logs_patient_id'), 'hydration_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_hydration_logs_recorded_at'), 'hydration_logs', ['recorded_at'], unique=False)
    op.create_table('location_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_events_patient_id'), 'location_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_location_events_recorded_at'), 'location_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_events_status'), 'location_events', ['status'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intake_level', sa.String(length=30), nullable=False),
    sa.Column('appetite', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_patient_id'), 'meal_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_meal_logs_recorded_at'), 'meal_logs', ['recorded_at'], unique=False)
    op.create_table('medical_documents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('storage_reference', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_documents_patient_id'), 'medical_documents', ['patient_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('scheduled_time', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('instructions', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medications_status'), 'medications', ['status'], unique=False)
    op.create_table('movement_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('log_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_km', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('active_minutes', sa.Integer(), nullable=False),
    sa.Column('activity_level', sa.String(length=30), nullable=False),
    sa.Column('last_movement_time', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_logs_log_date'), 'movement_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_movement_logs_patient_id'), 'movement_logs', ['patient_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('timestamp_label', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patient_preferences',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('likes', sa.Text(), nullable=False),
    sa.Column('dislikes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('pendant_devices',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('device_identifier', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('battery_percentage', sa.Integer(), nullable=False),
    sa.Column('gps_status', sa.String(length=30), nullable=False),
    sa.Column('speaker_status', sa.String(length=30), nullable=False),
    sa.Column('reminders_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('routines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=20), nullable=True),
    sa.Column('recurrence', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_patient_id'), 'routines', ['patient_id'], unique=False)
    op.create_table('safe_zones',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safe_zones_patient_id'), 'safe_zones', ['patient_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_event_type'), 'safety_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_safety_events_occurred_at'), 'safety_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_safety_events_patient_id'), 'safety_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_safety_events_resolved'), 'safety_events', ['resolved'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('sleep_start', sa.String(length=50), nullable=False),
    sa.Column('sleep_end', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.Column('night_wakeups', sa.Integer(), nullable=False),
    sa.Column('movement_level', sa.String(length=30), nullable=False),
    sa.Column('recorded_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_patient_id'), 'sleep_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sleep_logs_recorded_date'), 'sleep_logs', ['recorded_date'], unique=False)
    op.create_table('ai_feedbacks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('recommendation_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_response', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedbacks_patient_id'), 'ai_feedbacks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_feedbacks_recommendation_id'), 'ai_feedbacks', ['recommendation_id'], unique=False)
    op.create_table('cognitive_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('activity_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performance', sa.String(length=50), nullable=True),
    sa.Column('patient_response', sa.String(length=50), nullable=False),
    sa.Column('caregiver_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['cognitive_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_events_activity_id'), 'cognitive_events', ['activity_id'], unique=False)
    op.create_index(op.f('ix_cognitive_events_completed_at'), 'cognitive_events', ['completed_at'], unique=False)
    op.create_index(op.f('ix_cognitive_events_patient_id'), 'cognitive_events', ['patient_id'], unique=False)
    op.create_table('habilitation_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('activity_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assistance_level', sa.String(length=50), nullable=False),
    sa.Column('patient_response', sa.String(length=50), nullable=False),
    sa.Column('caregiver_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['habilitation_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habilitation_events_activity_id'), 'habilitation_events', ['activity_id'], unique=False)
    op.create_index(op.f('ix_habilitation_events_patient_id'), 'habilitation_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_habilitation_events_scheduled_at'), 'habilitation_events', ['scheduled_at'], unique=False)
    op.create_table('medication_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('medication_id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('medication_name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_events_medication_id'), 'medication_events', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_events_patient_id'), 'medication_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medication_events_scheduled_at'), 'medication_events', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_medication_events_status'), 'medication_events', ['status'], unique=False)
    op.create_table('recognition_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('familiar_person_id', sa.String(length=50), nullable=True),
    sa.Column('detected_name', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('camera_location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['familiar_person_id'], ['familiar_people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognition_events_detected_at'), 'recognition_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_recognition_events_patient_id'), 'recognition_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_recognition_events_status'), 'recognition_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_events_status'), table_name='recognition_events')
    op.drop_index(op.f('ix_recognition_events_patient_id'), table_name='recognition_events')
    op.drop_index(op.f('ix_recognition_events_detected_at'), table_name='recognition_events')
    op.drop_table('recognition_events')
    op.drop_index(op.f('ix_medication_events_status'), table_name='medication_events')
    op.drop_index(op.f('ix_medication_events_scheduled_at'), table_name='medication_events')
    op.drop_index(op.f('ix_medication_events_patient_id'), table_name='medication_events')
    op.drop_index(op.f('ix_medication_events_medication_id'), table_name='medication_events')
    op.drop_table('medication_events')
    op.drop_index(op.f('ix_habilitation_events_scheduled_at'), table_name='habilitation_events')
    op.drop_index(op.f('ix_habilitation_events_patient_id'), table_name='habilitation_events')
    op.drop_index(op.f('ix_habilitation_events_activity_id'), table_name='habilitation_events')
    op.drop_table('habilitation_events')
    op.drop_index(op.f('ix_cognitive_events_patient_id'), table_name='cognitive_events')
    op.drop_index(op.f('ix_cognitive_events_completed_at'), table_name='cognitive_events')
    op.drop_index(op.f('ix_cognitive_events_activity_id'), table_name='cognitive_events')
    op.drop_table('cognitive_events')
    op.drop_index(op.f('ix_ai_feedbacks_recommendation_id'), table_name='ai_feedbacks')
    op.drop_index(op.f('ix_ai_feedbacks_patient_id'), table_name='ai_feedbacks')
    op.drop_table('ai_feedbacks')
    op.drop_index(op.f('ix_sleep_logs_recorded_date'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_patient_id'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_safety_events_resolved'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_patient_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_occurred_at'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_event_type'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_safe_zones_patient_id'), table_name='safe_zones')
    op.drop_table('safe_zones')
    op.drop_index(op.f('ix_routines_patient_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_table('pendant_devices')
    op.drop_table('patient_preferences')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_movement_logs_patient_id'), table_name='movement_logs')
    op.drop_index(op.f('ix_movement_logs_log_date'), table_name='movement_logs')
    op.drop_table('movement_logs')
    op.drop_index(op.f('ix_medications_status'), table_name='medications')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_documents_patient_id'), table_name='medical_documents')
    op.drop_table('medical_documents')
    op.drop_index(op.f('ix_meal_logs_recorded_at'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_patient_id'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_location_events_status'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_recorded_at'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_patient_id'), table_name='location_events')
    op.drop_table('location_events')
    op.drop_index(op.f('ix_hydration_logs_recorded_at'), table_name='hydration_logs')
    op.drop_index(op.f('ix_hydration_logs_patient_id'), table_name='hydration_logs')
    op.drop_table('hydration_logs')
    op.drop_index(op.f('ix_habilitation_activities_patient_id'), table_name='habilitation_activities')
    op.drop_table('habilitation_activities')
    op.drop_index(op.f('ix_familiar_people_patient_id'), table_name='familiar_people')
    op.drop_table('familiar_people')
    op.drop_index(op.f('ix_doctor_care_plans_patient_id'), table_name='doctor_care_plans')
    op.drop_table('doctor_care_plans')
    op.drop_index(op.f('ix_cognitive_activities_patient_id'), table_name='cognitive_activities')
    op.drop_table('cognitive_activities')
    op.drop_index(op.f('ix_caregiver_patient_patient_id'), table_name='caregiver_patient')
    op.drop_index(op.f('ix_caregiver_patient_caregiver_id'), table_name='caregiver_patient')
    op.drop_table('caregiver_patient')
    op.drop_index(op.f('ix_care_team_members_patient_id'), table_name='care_team_members')
    op.drop_table('care_team_members')
    op.drop_index(op.f('ix_care_reports_report_type'), table_name='care_reports')
    op.drop_index(op.f('ix_care_reports_patient_id'), table_name='care_reports')
    op.drop_table('care_reports')
    op.drop_index(op.f('ix_behaviour_observations_patient_id'), table_name='behaviour_observations')
    op.drop_index(op.f('ix_behaviour_observations_observed_at'), table_name='behaviour_observations')
    op.drop_index(op.f('ix_behaviour_observations_observation_type'), table_name='behaviour_observations')
    op.drop_table('behaviour_observations')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_recommendations_status'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_patient_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ai_insights_patient_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_category'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
